### ISSUE TITLE
Bootstrap Project

### ISSUE THREAD

**Issue by runil** [knowitrickard/FlexiCharge-Android#21]
- [x] #23

**Comment by runil** [comment]
SDK version?

**Comment by knowitrickard** [comment]
> SDK version?

Go with level 30 (Android 11).

**Comment by runil** [comment]
> > SDK version?
> 
> 
> 
> Go with level 30 (Android 11).

One of our developers have an Android device on Android 10 (SDK 29). Is it fine for us to use it instead? It would allow us test on our own devices.

**Comment by knowitrickard** [comment]
> > > SDK version?
> > 
> > 
> > Go with level 30 (Android 11).
> 
> One of our developers have an Android device on Android 10 (SDK 29). Is it fine for us to use it instead? It would allow us test on our own devices.

That is perfectly fine!
